### ISSUE TITLE
Publish scala 2.13 version

### ISSUE THREAD

**Issue by vmandrychenko** [hipjim/scala-retry#25]
It seems that the library is built and tested for scala 2.13 but it is never published with 2.13. 

Are you planning on publishing it?

**Comment by hipjim** [comment]
Yes - planning to do so in the following days.

**Comment by automationeng** [comment]
Many people probably are facing an issue related to this, I'm just going to note it down here so that there can be more visibility as to why people upgrading to Scala 2.13 are having issues when running tests, etc...

```
An exception or error caused a run to abort: java.lang.NoClassDefFoundError: scala/Serializable 
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/Serializable
	at util.retry.blocking.RetryStrategy$.<init>(RetryStrategy.scala:117)
	at util.retry.blocking.RetryStrategy$.<clinit>(RetryStrategy.scala)
```

Looking forward to when this gets published, thanks!

**Comment by hipjim** [comment]
Done! Version 0.4.0 is out and supporting Scala 2.13.
